from django.db import models


class NombreBanco(models.TextChoices):
    SELECCIONE = " ","Seleccione banco"
    BANCO_ESTADO = "banco_estado", "Banco Estado"
    BANCO_CONSORCIO = "banco_consorcio", "Banco Consorcio"
    BANCO_DE_CHILE = "banco_de_chile", "Banco de Chile"
    BANCO_FALABELLA = "banco_falabella", "Banco Falabella"
    BANCO_INTERNACIONAL = "banco_internacional", "Banco Internacional"
    BANCO_ITAU = "banco_itau", "Banco Itaú"
    BANCO_RIPLEY = "banco_ripley", "Banco Ripley / Chek"
    BANCO_SANTANDER = "banco_santander", "Banco Santander"
    BANCO_SECURITY = "banco_security", "Banco Security"
    BCI = "bci", "BCI / MACH"
    BICE = "bice", "Banco BICE"
    COOPEUCH = "coopeuch", "Coopeuch"
    CORPBANCA = "corpbanca", "CorpBanca"
    GLOBAL66 = "global66", "Global66"
    HSBC = "hsbc", "HSBC Bank"
    JPMORGAN = "jpmorgan", "JP Morgan"
    LA_POLAR = "la_polar", "La Polar Prepago"
    MERCADO_PAGO = "mercado_pago", "Mercado Pago"
    METRO_MUV = "metro_muv", "Metro Muv"
    MUFG = "mufg", "MUFG Bank, Ltd"
    LOS_HEROES = "los_heroes", "Prepago Los Héroes"
    TENPO = "tenpo", "Prepago Tenpo"
    SCOTIABANK = "scotiabank", "Scotiabank Desarrollo"
    TANNER = "tanner", "Tanner"
    CAJA_LOS_ANDES = "caja_los_andes", "Caja Los Andes"