# Generated by Django 6.0.3 on 2026-03-25 01:33

import alke_wallet_app.models.wallet
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_banco", models.CharField(max_length=100)),
                ("numero_cuenta", models.CharField(max_length=30)),
                (
                    "tipo_cuenta",
                    models.CharField(
                        choices=[
                            ("vista", "Vista"),
                            ("corriente", "Corriente"),
                            ("chequera_electronica", "Chequera electrónica"),
                            ("cuenta_rut", "Cuenta Rut"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuenta_bancaria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarjeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_tarjeta", models.CharField(max_length=19)),
                (
                    "tipo_tarjeta",
                    models.CharField(
                        choices=[
                            ("credito", "Crédito"),
                            ("debito", "Débito"),
                            ("prepago", "Prepago"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_expiracion", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cuenta_bancaria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tarjetas",
                        to="alke_wallet_app.cuentabancaria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        default=alke_wallet_app.models.wallet.generar_codigo,
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("divisa", models.CharField(default="CLP", max_length=10)),
                ("estado", models.CharField(default="activa", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_destinatario",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "tipo_transaccion",
                    models.CharField(
                        choices=[
                            ("compra", "Compra"),
                            ("transferencia", "Transferencia"),
                            ("deposito", "Depósito"),
                            ("retiro", "Retiro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_direccion",
                    models.CharField(
                        choices=[("debito", "Débito"), ("credito", "Crédito")],
                        max_length=10,
                    ),
                ),
                (
                    "origen_fondo",
                    models.CharField(
                        choices=[("propio", "Propio"), ("tercero", "Tercero")],
                        default="propio",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                (
                    "referencia",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cuenta_banco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="alke_wallet_app.cuentabancaria",
                    ),
                ),
                (
                    "tarjeta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="alke_wallet_app.tarjeta",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="alke_wallet_app.wallet",
                    ),
                ),
                (
                    "wallet_tercero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacciones_recibidas",
                        to="alke_wallet_app.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Destinatario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_codigo",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("apellido", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=50)),
                ("apodo", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mis_destinatarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destinatarios",
                        to="alke_wallet_app.wallet",
                    ),
                ),
            ],
        ),
    ]
