# Generated by Django 6.0.3 on 2026-03-10 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_banco", models.CharField(max_length=100)),
                ("numero_cuenta", models.CharField(max_length=30)),
                (
                    "tipo_cuenta",
                    models.CharField(
                        choices=[
                            ("vista", "Vista"),
                            ("corriente", "Corriente"),
                            ("chequera_electronica", "Chequera electrónica"),
                            ("cuenta_rut", "Cuenta Rut"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarjeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_tarjeta", models.CharField(max_length=20)),
                (
                    "tipo_tarjeta",
                    models.CharField(
                        choices=[
                            ("credito", "Crédito"),
                            ("debito", "Débito"),
                            ("prepago", "Prepago"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_expiracion", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_transaccion",
                    models.CharField(
                        choices=[
                            ("compra", "Compra"),
                            ("transferencia", "Transferencia"),
                            ("deposito", "Depósito"),
                            ("retiro", "Retiro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_direccion",
                    models.CharField(
                        choices=[("debito", "Débito"), ("credito", "Crédito")],
                        max_length=10,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cuenta_banco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="alke_wallet_app.cuentabancaria",
                    ),
                ),
                (
                    "tarjeta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="alke_wallet_app.tarjeta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("alimentacion", "Alimentación"),
                            ("transporte", "Transporte"),
                            ("servicio", "Servicio"),
                            ("entretenimiento", "Entretenimiento"),
                        ],
                        max_length=15,
                    ),
                ),
                ("comercio", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compra",
                        to="alke_wallet_app.transaccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("divisa", models.CharField(default="CLP", max_length=10)),
                ("estado", models.CharField(default="activa", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaccion",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="alke_wallet_app.wallet"
            ),
        ),
    ]
