# Generated by Django 6.0.3 on 2026-03-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alke_wallet_app", "0002_remove_destinatario_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarjeta",
            name="marca",
            field=models.CharField(default="credito", max_length=20),
        ),
    ]
