# Generated by Django 6.0.3 on 2026-03-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alke_wallet_app", "0003_tarjeta_marca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarjeta",
            name="marca",
            field=models.CharField(default="visa", max_length=20),
        ),
    ]
