# Generated by Django 6.0.3 on 2026-03-26 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alke_wallet_app", "0004_alter_tarjeta_marca"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuentabancaria",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cuentas_bancarias",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
