# Generated by Django 6.0.3 on 2026-03-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alke_wallet_app", "0005_alter_cuentabancaria_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuentabancaria",
            name="nombre_banco",
            field=models.CharField(
                choices=[
                    (" ", "Seleccione banco"),
                    ("banco_estado", "Banco Estado"),
                    ("banco_consorcio", "Banco Consorcio"),
                    ("banco_de_chile", "Banco de Chile"),
                    ("banco_falabella", "Banco Falabella"),
                    ("banco_internacional", "Banco Internacional"),
                    ("banco_itau", "Banco Itaú"),
                    ("banco_ripley", "Banco Ripley / Chek"),
                    ("banco_santander", "Banco Santander"),
                    ("banco_security", "Banco Security"),
                    ("bci", "BCI / MACH"),
                    ("bice", "Banco BICE"),
                    ("coopeuch", "Coopeuch"),
                    ("corpbanca", "CorpBanca"),
                    ("global66", "Global66"),
                    ("hsbc", "HSBC Bank"),
                    ("jpmorgan", "JP Morgan"),
                    ("la_polar", "La Polar Prepago"),
                    ("mercado_pago", "Mercado Pago"),
                    ("metro_muv", "Metro Muv"),
                    ("mufg", "MUFG Bank, Ltd"),
                    ("los_heroes", "Prepago Los Héroes"),
                    ("tenpo", "Prepago Tenpo"),
                    ("scotiabank", "Scotiabank Desarrollo"),
                    ("tanner", "Tanner"),
                    ("caja_los_andes", "Caja Los Andes"),
                ],
                max_length=100,
            ),
        ),
    ]
