# Generated by Django 6.0.3 on 2026-03-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alke_wallet_app", "0006_alter_cuentabancaria_nombre_banco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaccion",
            name="tipo_direccion",
            field=models.CharField(
                choices=[
                    ("debito", "Débito"),
                    ("credito", "Crédito"),
                    ("prepago", "Prepago"),
                ],
                max_length=10,
            ),
        ),
    ]
